### ISSUE TITLE
Unable to calculate votes

### ISSUE THREAD

**Issue by ro-savage** [julia-mareike/parliament#17]
Awesome tool you two have built and looks great! I had fun playing with the polls and past results.

I tried to calculate a percentage, but couldn't get it working. See screenshots:

**Here I am unable to press calculate**
![image](https://user-images.githubusercontent.com/9244507/94890599-29785400-04dc-11eb-9d4b-6aee5818ebbf.png)

**Here I have gone over and get the warning**
![image](https://user-images.githubusercontent.com/9244507/94890620-3c8b2400-04dc-11eb-91e8-7ab296326ee2.png)

I tried entering 0 for parties and it won't let me enter 0.
And I tried entering 1 for every party + 55 for labour to reach 71. But the button was still greyed out.

Not sure if I am missing something or?

**Comment by ro-savage** [comment]
My mistake. I just don't understand the MMP system well enough.

The first one is the party votes, and the 2nd field is electoral area wins.

I had mistakenly though the first input was just text saying what party it was, not an actual input :)

**Comment by julia-mareike** [comment]
oh no lol, sorry for this stressful experience! i confess our UX research was minimal at best haha.
thanks for your kind words 😎
